# Generated by Django 6.1 on 2026-08-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120, verbose_name='Lavozim')),
                ('company', models.CharField(max_length=120, verbose_name='Tashkilot')),
                ('start_date', models.CharField(help_text='Masalan: 2023-yil yanvar', max_length=30, verbose_name='Boshlanish')),
                ('end_date', models.CharField(blank=True, help_text="Bo'sh qoldirilsa 'Hozirgacha' deb chiqadi", max_length=30, verbose_name='Tugash')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Ish tajribasi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ismingiz Familiyangiz', max_length=120, verbose_name='F.I.Sh')),
                ('title', models.CharField(default='Backend dasturchi', max_length=160, verbose_name='Kasbiy unvon')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Qisqa shior')),
                ('about', models.TextField(verbose_name="O'zim haqimda")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Manzil')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='Rezyume (PDF)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil rasmi')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(max_length=220, verbose_name='Qisqacha tavsif')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('tech_stack', models.CharField(help_text='Masalan: Django, PostgreSQL, Vue.js', max_length=200, verbose_name='Texnologiyalar (vergul bilan)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Rasm')),
                ('repo_url', models.URLField(blank=True, verbose_name='Manba kod (GitHub)')),
                ('live_url', models.URLField(blank=True, verbose_name='Jonli havola')),
                ('featured', models.BooleanField(default=False, verbose_name='Asosiy loyihami?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('tools', 'Vositalar')], default='backend', max_length=20, verbose_name='Turkum')),
                ('level', models.PositiveSmallIntegerField(default=80, verbose_name='Daraja (0-100)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
